apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: dev-3scale-app
    namespace: openshift-gitops
  spec:
    destination:
      namespace: dev-3scale
      server: https://kubernetes.default.svc
    project: dev-3scale
    source:
      path: overlay/dev
      repoURL: https://github.com/barmolla/3scale-gitops.git
      targetRevision: main
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
kind: List
metadata: {}