apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: uat-reprocann
- apiVersion: v1
  data:
    password: YWRtaW4xMjM=
    username: YWRtaW4=
  kind: Secret
  metadata:
    annotations:
      tekton.dev/docker-0: https://10.10.103.100:8123
    name: nexus-credentials
    namespace: uat-reprocann
  type: kubernetes.io/basic-auth
- apiVersion: v1
  data:
    known_hosts: MTkyLjE2OC4xLjEyIGVjZHNhLXNoYTItbmlzdHAyNTYgQUFBQUUyVmpaSE5oTFhOb1lUSXRibWx6ZEhBeU5UWUFBQUFJYm1semRIQXlOVFlBQUFCQkJKeGxvcEJjcHNPZjZ1ckIzYUVjRVdSTE14VEU2SVc3S25HNzRUYU5OSXVVMEp3TVpvaGpiUk8vcHJ1VWY3b3Fyc1dDQ2cwK2JGWjQ4MFhhcHdnMHFNdz0KMTkyLjE2OC4xNDQuMjEwIGVjZHNhLXNoYTItbmlzdHAyNTYgQUFBQUUyVmpaSE5oTFhOb1lUSXRibWx6ZEhBeU5UWUFBQUFJYm1semRIQXlOVFlBQUFCQkJJazIvWFpwNmlxYmRiWkVQVEhNVGk3VjQ0bG40aTUvTTFsbjlVRStuNkhZZDE1TVlpYmwwUUZPZlp5QTVBQ3AyWVplbU5sTi80VnMvM2RmOHdZTzM4ND0KYmFzdGlvbi5kNWJlLnNhbmRib3gxMjUwLm9wZW50bGMuY29tLDE4LjE4OC4yMTguNSBlY2RzYS1zaGEyLW5pc3RwMjU2IEFBQUFFMlZqWkhOaExYTm9ZVEl0Ym1semRIQXlOVFlBQUFBSWJtbHpkSEF5TlRZQUFBQkJCQlVsdnZFazI5RFNwTXh3VHZjV0JJY3ZZemw4NGVvdUtzTUltNkFzQmlGYmZXRlZZY29OenlsVTlmdU5OL1p6SXVJS3BlSTE3WXZ0cUg0UytSQVlOR0k9CmJhc3Rpb24uNjdiMi5zYW5kYm94NzU3Lm9wZW50bGMuY29tLDMuMjMuMTMuMTMwIGVjZHNhLXNoYTItbmlzdHAyNTYgQUFBQUUyVmpaSE5oTFhOb1lUSXRibWx6ZEhBeU5UWUFBQUFJYm1semRIQXlOVFlBQUFCQkJQbFk2NXVyV25uMGJEWjJMOGRMVWY2dnhzWHJKVFRvTktodjZmZ0F1MWpXTlhvL0xqekZVK2l6ZitJUU5MS0tFTnNGZmJPTFVYUThqVjUzQnhtbE5TUT0KYmFzdGlvbi4yZGM1LnNhbmRib3g2NTMub3BlbnRsYy5jb20sMy4xMzguMTYyLjg4IGVjZHNhLXNoYTItbmlzdHAyNTYgQUFBQUUyVmpaSE5oTFhOb1lUSXRibWx6ZEhBeU5UWUFBQUFJYm1semRIQXlOVFlBQUFCQkJDRm1ubS9EOE1UbGpXTDVFRWMwd2JDbFZWTEZGTThCVjR2bnAwYWpxWnRDT1pvRDJCVlc0SktqMFNOWGxpK1BlRnBpM1dvMnNla0lLZFFsVTVwMytBOD0KYmFzdGlvbi5lMDdiLnNhbmRib3g2NDcub3BlbnRsYy5jb20sMTguMTE3LjMyLjE3NSBlY2RzYS1zaGEyLW5pc3RwMjU2IEFBQUFFMlZqWkhOaExYTm9ZVEl0Ym1semRIQXlOVFlBQUFBSWJtbHpkSEF5TlRZQUFBQkJCQjI2aHE2ZU04cE8rRHhLbWtsK2JvV3NPOXBWRUlLRW1BbCtPcWhtMnFsL0xaNEN4L2cyZkh2b2EyVGpXcGZsaWZlYzJIRFlYSzZtcWMreitPTk03UVE9CmJhc3Rpb24uZDhhYi5zYW5kYm94MTE2OC5vcGVudGxjLmNvbSwzLjEyLjExMy4xMjAgZWNkc2Etc2hhMi1uaXN0cDI1NiBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6ZEhBeU5UWUFBQUJCQkk3c0pVMDJOd0VjU2hQZlBQNFRHZjVJNHhjUDN2N1E1cnZaNXNnbFRQLzNjd3phZFo1YjhvSng1ejV4azVZZXhYNWdMMm44KzhjNEd0MDBuZUx0Q0RNPQpiYXN0aW9uLjQ5NzUuc2FuZGJveDczMC5vcGVudGxjLmNvbSwzLjEzMC4yNTAuMTk3IGVjZHNhLXNoYTItbmlzdHAyNTYgQUFBQUUyVmpaSE5oTFhOb1lUSXRibWx6ZEhBeU5UWUFBQUFJYm1semRIQXlOVFlBQUFCQkJOZjBCTkhRWjBRK2hicW4vbEpxb0VpTXp4NnRsbDRzU2JwYkdEMmpKN2NjeGtYSlp2OGwzbW5meGx2dUJSSHBvNWl2U2sxZlZ6cUNMYzdSbkYwaU0wST0KYmFzdGlvbi4zMmFhLnNhbmRib3gxMDk4Lm9wZW50bGMuY29tLDMuMjMuMjUxLjIyMSBlY2RzYS1zaGEyLW5pc3RwMjU2IEFBQUFFMlZqWkhOaExYTm9ZVEl0Ym1semRIQXlOVFlBQUFBSWJtbHpkSEF5TlRZQUFBQkJCT1RLS296MjA5QVpPc25XcUd0bEVPaTZ0a0FMMDVsZG52U0c0RFdabUpLZ0dmVmhraDdWR0J1bkN0UDJZRjlhSnJ4TWtmYWdlbjE1dGNsVGdTWXFBSnc9CmJhc3Rpb24uYjFhMi5zYW5kYm94MTA4MC5vcGVudGxjLmNvbSwzLjEzMS4yMzQuNzIgZWNkc2Etc2hhMi1uaXN0cDI1NiBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6ZEhBeU5UWUFBQUJCQkJiMWJKMXdvenNUdFYraUNaTzFDT211OTlSYXphdCtuZnl4ZVFOaWNmekNnT0lYc0RBTitENUhpelJwZ3JwdCtaZ3B6T1ZVNnhEdk1KNmZsNyttNzNVPQpiYXN0aW9uLjJhYTUuc2FuZGJveDI0Ny5vcGVudGxjLmNvbSwzLjEzNi4zMy4xOTcgZWNkc2Etc2hhMi1uaXN0cDI1NiBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6ZEhBeU5UWUFBQUJCQk0xUDZFdFFaY0g3dmJEQ2t4OGwzQXVhcUpmc3BwOU1tRytDNnZaeWF6KzFOaDZhU1AvREtHSnA5cWVOK1dBM0JlR0RFb2JwWjlBT1d0TVBNTjNHS29nPQpiYXN0aW9uLjMwNGQuc2FuZGJveDUzNS5vcGVudGxjLmNvbSwzLjE5LjIzNS45MCBlY2RzYS1zaGEyLW5pc3RwMjU2IEFBQUFFMlZqWkhOaExYTm9ZVEl0Ym1semRIQXlOVFlBQUFBSWJtbHpkSEF5TlRZQUFBQkJCQmdiVk55RUVobVJ1MWtkcjZVZkxSN3ZlbEQwS2h5RXpTU3hvLzNJVzNNL2RHWmlGM1NMNEFOS3l5T2RKWWVHVXQyZFVYTTIzVG1jdE54aGcyWXA2RVU9CmJhc3Rpb24uNmNiNy5zYW5kYm94NTM5Lm9wZW50bGMuY29tLDE4LjIyMy4yMDQuMjA4IGVjZHNhLXNoYTItbmlzdHAyNTYgQUFBQUUyVmpaSE5oTFhOb1lUSXRibWx6ZEhBeU5UWUFBQUFJYm1semRIQXlOVFlBQUFCQkJQUUF6N05nYisyR3JxUlc4ZE5jOFJnTVJ2bDJtTkNvNnF4ZlMyNnpyN1p1TkxFemJ4VHFjNVJaM2ROQXc0dlhxOVdZWjVML3FHaUFMbXhESkc0b0lqUT0KMTkyLjE2OC4xLjEyIHNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQmdRQy92R1JuSjNMUlRhRUc2ZmFiZjR3dDh0VUZ1NExRd1IxOGhiK1dLZWpaLzNxZXZqZXZiSXBGWGNFdkhlL0pkVXByQ2VjdWdSNFZtLzcxR0cxc0FTUENHYXhYVUYvTC96OHhjOEl6V1k4ZytWdVZtMEsyUDJBTGdPZzAwYmx0MVdZYkhuRkZKTFk4WGxZSG1lQTNRdG5VcSs5bmkxY2VHbnRQR0lwQUYyYks3ODgwQ3dHbHhwa28wR1UvZ2xpWkIycE0wMzlpdWYxMWRyMm80aFMxU0J5MzZRWFpobytWNTVnY1pzNDZ3eTY3dHo2cURSZ0xpRlB0WS9HZU5PVXExWFBYSVZya2kyUXdlT0hjcXQrUUdvaEgxWEpBandSUUs2eERadDF3YjZtVzVUbHlkZTlUVTJtMEZBcmRTOWxkQldzWmpYdXdjdzZWa2tNSCt5eXlkU0owdXduYi9ZcUd4cTNBYlh1ZlRxSC9lQk1JRXovUGw0SUd3Q2pObkQzejRHaE1KYkd6NTJISkExRGowbUNaUWpJRDVaZ2ZvVkNDNFgzRW56dUpQUEZLNmtzZzdpYTdyakRhN2hOSFYrWnJ6N3NyWTJlSEFjWTNtZW5TbnhOUmRmMHRSR2JmdkRnbTl6OUtwcWpNQjc1U3hNZU5GNlJlOUN1SkxFL1ZYbk5TN3lzPQoxOTIuMTY4LjEuMTIgc3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUNxbUVFaEtmemE3RmtMTDM5aG93NDcrdDlNb05LMTZ2VlExcWRKRE5tWFoKMTkyLjE2OC4xLjE0IHNzaC1lZDI1NTE5IEFBQUFDM056YUMxbFpESTFOVEU1QUFBQUlDcW1FRWhLZnphN0ZrTEwzOWhvdzQ3K3Q5TW9OSzE2dlZRMXFkSkRObVhaCg==
    ssh-privatekey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCVllna01yTWF1SFhsdlN4alB5MS85bDFJcjNNMW8xV3lNYWZGaFJGNnpTd0FBQUppa0RFamlwQXhJCjRnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQlZZZ2tNck1hdUhYbHZTeGpQeTEvOWwxSXIzTTFvMVd5TWFmRmhSRjZ6U3cKQUFBRUFOWVk3MkF2QnRlWWZOTjB4Qmd4R3FwcW9kSDVQSmhNaDdNWXNkdG1FcFhsVmlDUXlzeHE0ZGVXOUxHTS9MWC8yWApVaXZjeldqVmJJeHA4V0ZFWHJOTEFBQUFGR3hsZW1OaGJtOHVaR0ZBWjIxaGFXd3VZMjl0QVE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
  kind: Secret
  metadata:
    annotations:
      tekton.dev/git-0: github.com
    name: repository-credentials
    namespace: uat-reprocann
  type: kubernetes.io/ssh-auth
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pipeline
    namespace: uat-reprocann
  secrets:
  - name: repository-credentials
  - name: nexus-credentials
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: pipeline-puller
    namespace: qa-reprocann
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: pipeline-puller
  subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: uat-reprocann
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: workspace-pvc
    namespace: uat-reprocann
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
kind: List
metadata: {}
