apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: dev-personal-service-app
    namespace: openshift-gitops
  spec:
    destination:
      namespace: dev-personal-service
      server: https://kubernetes.default.svc
    project: dev-personal-service
    source:
      path: overlay/dev
      repoURL: git@github.com:damianlezcano/reprocann-gitops.git
      targetRevision: main
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
kind: List
metadata: {}
