apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: 3scale
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: Namespace
  - group: '*'
    kind: Secret
  - group: '*'
    kind: PersistentVolumeClaim
  - group: '*'
    kind: Pipeline
  - group: '*'
    kind: ServiceAccount
  - group: '*'
    kind: LimitRange
  - group: "*"
    kind: ResourceQuota
  project: 'openshift-gitops'
  destinations:
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc
  - namespace: 3scale
    server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
  - group: ""
    kind: NetworkPolicy
  sourceRepos:
  - '*'
  source:
    directory:
      recurse: true
    path: ocp01/proyectos/3scale
    repoURL: https://github.com/barmolla/openshift-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true