apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: uat-reprocann-backend-app
    namespace: openshift-gitops
  spec:
    destination:
      namespace: uat-reprocann
      server: https://kubernetes.default.svc
    ignoreDifferences:
    - group: '*'
      jsonPointers:
      - /spec/tls
      kind: Route
    project: uat-reprocann
    source:
      path: overlays/uat
      repoURL: ssh://git@github.com/reprocann-gitops.git
      targetRevision: main
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
kind: List
metadata: {}
