apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
#metadata:
#  annotations:
#    apps.3scale.net/apimanager-threescale-version: "2.13"
#    apps.3scale.net/threescale-operator-version: 0.10.1
#  creationTimestamp: "2022-05-03T20:00:18Z"
#  generation: 6
#  name: apimanager
#  namespace: 3scale
#  resourceVersion: "1599067447"
#  uid: e25d891f-39d4-4690-88c4-89a11b75276d
spec:
  apicast:
    managementAPI: status
    openSSLVerify: false
    productionSpec:
      logLevel: debug
      replicas: 1
    registryURL: http://apicast-staging:8090/policies
    responseCodes: true
    stagingSpec:
      logLevel: debug
      replicas: 1
  appLabel: 3scale-api-management
  backend:
    cronSpec:
      replicas: 1
    listenerSpec:
      replicas: 1
    workerSpec:
      replicas: 1
  imageStreamTagImportInsecure: false
  resourceRequirementsEnabled: true
  system:
    appSpec:
      replicas: 1
    database:
      mysql:
        persistentVolumeClaim:
          resources:
            requests: 1Gi
    fileStorage:
      persistentVolumeClaim:
        resources:
          requests: 1Gi
        storageClassName: nfs02
    sidekiqSpec:
      replicas: 1
    sphinxSpec: {}
  tenantName: 3scale
  #https://console-openshift-console.apps.cluster-99n9j.99n9j.sandbox2175.opentlc.com
  #https://console-openshift-console.apps.osnoprod01.aseconecta.com.ar
  #wildcardDomain: 3scale.apps.osnoprod01.aseconecta.com.ar
  wildcardDomain: 3scale.apps.cluster-99n9j.99n9j.sandbox2175.opentlc.com
  zync:
    appSpec:
      replicas: 1
    queSpec:
      replicas: 1
#status:
#  conditions:
#  - lastTransitionTime: "2024-02-02T16:46:16Z"
#    status: "True"
#    type: Available
#  deployments:
#    ready:
#    - apicast-production
#    - apicast-staging
#    - backend-cron
#    - backend-listener
#    - backend-redis
#    - backend-worker
#    - system-app
#    - system-memcache
#    - system-mysql
#    - system-redis
#    - system-sidekiq
#    - system-sphinx
#    - zync
#    - zync-database
#    - zync-que
