apiVersion: v1
kind: Secret
metadata:
  name: gitlab-ssh-repo-creds
  namespace: openshift-gitops
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  sshPrivateKey: >-
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCVllna01yTWF1SFhsdlN4alB5MS85bDFJcjNNMW8xV3lNYWZGaFJGNnpTd0FBQUppa0RFamlwQXhJCjRnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQlZZZ2tNck1hdUhYbHZTeGpQeTEvOWwxSXIzTTFvMVd5TWFmRmhSRjZ6U3cKQUFBRUFOWVk3MkF2QnRlWWZOTjB4Qmd4R3FwcW9kSDVQSmhNaDdNWXNkdG1FcFhsVmlDUXlzeHE0ZGVXOUxHTS9MWC8yWApVaXZjeldqVmJJeHA4V0ZFWHJOTEFBQUFGR3hsZW1OaGJtOHVaR0ZBWjIxaGFXd3VZMjl0QVE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
  url: Z2l0QGdpdGh1Yi5jb20K
type: Opaque